import type { Prompt } from '../components/library/PromptCard';

const creators = [
  { name: 'Sarah Jenkins', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=faces', handle: '@sarahj' },
  { name: 'Marcus Chen', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=faces', handle: '@marcus_chen' },
  { name: 'Elena Rodriguez', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=faces', handle: '@elena_art' },
  { name: 'David Kim', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=faces', handle: '@dkim_design' },
];

export const mockPrompts: Prompt[] = [
  {
    id: '1',
    slug: 'cinematic-cyberpunk-city',
    title: 'Cinematic Cyberpunk Cityscape with Neon Reflections',
    prompt_text: 'A highly detailed cinematic shot of a futuristic cyberpunk city at night, neon lights reflecting in puddles, rain, flying cars in the distance, 8k resolution, photorealistic, unreal engine 5 render, volumetric lighting.',
    image_url: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=800&q=80',
    tags: ['cyberpunk', 'city', 'neon', 'futuristic'],
    model: 'Midjourney v6',
    style: 'Cinematic',
    view_count: 12450,
    save_count: 3200,
    creator: creators[0]
  },
  {
    id: '2',
    slug: 'minimalist-logo-design',
    title: 'Minimalist Tech Startup Logo',
    prompt_text: 'A minimalist logo design for a tech startup, abstract geometric shape, gradient blue and purple, flat design, white background, vector style, clean lines, modern.',
    image_url: 'https://images.unsplash.com/photo-1557682224-5b8590cd9ec5?w=800&q=80',
    tags: ['logo', 'minimalist', 'branding', 'vector'],
    model: 'DALL-E 3',
    style: 'Graphic Design',
    view_count: 8900,
    save_count: 1540,
    creator: creators[1]
  },
  {
    id: '3',
    slug: 'watercolor-botanical-illustration',
    title: 'Vintage Watercolor Botanical Illustration',
    prompt_text: 'A vintage watercolor botanical illustration of a monstera plant, soft pastel colors, detailed leaves, paper texture, scientific illustration style, muted tones.',
    image_url: 'https://images.unsplash.com/photo-1545241047-6083a36a0d1d?w=800&q=80',
    tags: ['watercolor', 'botanical', 'vintage', 'illustration'],
    model: 'Midjourney v6',
    style: 'Illustration',
    view_count: 5600,
    save_count: 890,
    creator: creators[2]
  },
  {
    id: '4',
    slug: '3d-isometric-room',
    title: 'Cozy 3D Isometric Gaming Room',
    prompt_text: 'A cozy 3D isometric gaming room, neon purple and blue lighting, dual monitors, mechanical keyboard, bean bag chair, posters on wall, soft clay render style, octane render, trending on artstation.',
    image_url: 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800&q=80',
    tags: ['3d', 'isometric', 'room', 'gaming'],
    model: 'Midjourney v5.2',
    style: '3D Render',
    view_count: 15200,
    save_count: 4100,
    creator: creators[3]
  },
  {
    id: '5',
    slug: 'portrait-fantasy-elf',
    title: 'High Fantasy Elf Portrait',
    prompt_text: 'A close up portrait of a beautiful high fantasy elf, glowing ethereal eyes, silver hair, intricate silver armor with emerald accents, mystical forest background, soft natural lighting, masterpiece, highly detailed.',
    image_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80',
    tags: ['portrait', 'fantasy', 'elf', 'character'],
    model: 'Stable Diffusion XL',
    style: 'Portrait',
    view_count: 7300,
    save_count: 1200,
    creator: creators[0]
  },
  {
    id: '6',
    slug: 'abstract-fluid-art',
    title: 'Vibrant Abstract Fluid Art',
    prompt_text: 'Vibrant abstract fluid art, swirling colors of gold, teal, and magenta, macro photography, liquid ink dynamics, metallic flakes, high contrast, 8k, crisp.',
    image_url: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&q=80',
    tags: ['abstract', 'fluid', 'art', 'colorful'],
    model: 'Midjourney v6',
    style: 'Abstract',
    view_count: 4200,
    save_count: 650,
    creator: creators[1]
  },
  {
    id: '7',
    slug: 'sci-fi-space-station',
    title: 'Massive Sci-Fi Space Station',
    prompt_text: 'A massive sci-fi space station orbiting a ringed gas giant, intricate docking bays, glowing blue engines, deep space background, cinematic lighting, epic scale, concept art.',
    image_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80',
    tags: ['space', 'sci-fi', 'station', 'epic'],
    model: 'DALL-E 3',
    style: 'Concept Art',
    view_count: 11050,
    save_count: 2800,
    creator: creators[2]
  },
  {
    id: '8',
    slug: 'cute-pixar-character',
    title: 'Cute Pixar Style Robot Character',
    prompt_text: 'A cute little rusty robot character holding a glowing dandelion, pixar style 3d animation, big expressive eyes, overgrown forest floor setting, soft magical lighting, highly detailed.',
    image_url: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80',
    tags: ['cute', 'robot', 'pixar', '3d'],
    model: 'Midjourney v6',
    style: '3D Animation',
    view_count: 18900,
    save_count: 5200,
    creator: creators[3]
  },
  {
    id: '9',
    slug: 'architectural-interior-design',
    title: 'Modern Japandi Living Room',
    prompt_text: 'Interior design of a modern Japandi style living room, natural wood, beige linen sofa, large windows showing a bamboo garden, soft sunlight, minimalist, wabi-sabi, architectural digest photography.',
    image_url: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80',
    tags: ['architecture', 'interior', 'japandi', 'minimalist'],
    model: 'Midjourney v6',
    style: 'Photography',
    view_count: 9400,
    save_count: 2100,
    creator: creators[0]
  },
  {
    id: '10',
    slug: 'food-photography-burger',
    title: 'Gourmet Burger Food Photography',
    prompt_text: 'Professional food photography of a gourmet double cheeseburger, melting cheddar, crispy bacon, brioche bun, flying ingredients, dark moody background, studio lighting, highly appetizing, 8k.',
    image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    tags: ['food', 'burger', 'photography', 'appetizing'],
    model: 'Stable Diffusion XL',
    style: 'Food Photography',
    view_count: 6100,
    save_count: 950,
    creator: creators[1]
  },
  {
    id: '11',
    slug: 'steampunk-flying-ship',
    title: 'Epic Steampunk Airship',
    prompt_text: 'An epic steampunk airship flying through dramatic sunset clouds, brass and copper details, turning gears, giant balloons, smokestacks, highly detailed, trending on artstation, fantasy concept art.',
    image_url: 'https://images.unsplash.com/photo-1524185962737-ea7c028a12cd?w=800&q=80',
    tags: ['steampunk', 'airship', 'fantasy', 'epic'],
    model: 'Midjourney v5.2',
    style: 'Concept Art',
    view_count: 8200,
    save_count: 1750,
    creator: creators[2]
  },
  {
    id: '12',
    slug: 'line-art-tattoo-design',
    title: 'Minimalist Line Art Tattoo',
    prompt_text: 'A minimalist line art tattoo design of a sun and moon intertwined with wildflowers, single continuous line, black ink, white background, simple, elegant.',
    image_url: 'https://images.unsplash.com/photo-1611078813632-6a56e02619cd?w=800&q=80',
    tags: ['tattoo', 'lineart', 'minimalist', 'design'],
    model: 'DALL-E 3',
    style: 'Line Art',
    view_count: 14300,
    save_count: 3800,
    creator: creators[3]
  },
  {
    id: '13',
    slug: 'macro-photography-eye',
    title: 'Extreme Macro Human Eye',
    prompt_text: 'Extreme macro photography of a human eye, golden iris, reflecting a galaxy, highly detailed textures, dramatic lighting, sharp focus, 85mm lens.',
    image_url: 'https://images.unsplash.com/photo-1542194680-e836cb1e8b7f?w=800&q=80',
    tags: ['macro', 'eye', 'photography', 'detailed'],
    model: 'Midjourney v6',
    style: 'Macro Photography',
    view_count: 5800,
    save_count: 1100,
    creator: creators[0]
  },
  {
    id: '14',
    slug: 'pixel-art-landscape',
    title: '16-bit Pixel Art Landscape',
    prompt_text: '16-bit pixel art of a tranquil waterfall in a lush forest, glowing fireflies, retro gaming style, vibrant colors, nostalgic, beautiful scenery.',
    image_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&q=80',
    tags: ['pixelart', 'landscape', 'retro', 'gaming'],
    model: 'Midjourney v5.2',
    style: 'Pixel Art',
    view_count: 7900,
    save_count: 1420,
    creator: creators[1]
  },
  {
    id: '15',
    slug: 'ui-ux-dashboard-design',
    title: 'Modern UI/UX Dashboard',
    prompt_text: 'A modern UI/UX dashboard design for a financial app, glassmorphism, dark mode, glowing purple and blue accents, clean charts, dribbble style, highly detailed, neat layout.',
    image_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    tags: ['ui', 'ux', 'dashboard', 'design'],
    model: 'DALL-E 3',
    style: 'UI Design',
    view_count: 16500,
    save_count: 4500,
    creator: creators[2]
  }
];
