import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft } from "lucide-react";
import { SITE_URL } from "@/lib/trends";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Use — love4prompts" },
      {
        name: "description",
        content:
          "The Terms of Use governing access to and use of love4prompts — acceptable use, intellectual property, user-generated content, and disclaimers.",
      },
      { name: "keywords", content: "love4prompts terms of use, legal, acceptable use, intellectual property" },
      { name: "robots", content: "index,follow" },
      { property: "og:title", content: "Terms of Use — love4prompts" },
      {
        property: "og:description",
        content:
          "Acceptable use, intellectual property, user-generated content, and disclaimers for love4prompts.",
      },
      { property: "og:url", content: `${SITE_URL}/terms` },
      { property: "og:type", content: "article" },
      { property: "og:site_name", content: "love4prompts" },
      { name: "twitter:card", content: "summary" },
      { name: "twitter:title", content: "Terms of Use — love4prompts" },
      {
        name: "twitter:description",
        content: "The Terms of Use for love4prompts.",
      },
    ],
    links: [{ rel: "canonical", href: `${SITE_URL}/terms` }],
    scripts: [
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "WebPage",
          name: "Terms of Use",
          url: `${SITE_URL}/terms`,
          inLanguage: "en",
          isPartOf: { "@type": "WebSite", name: "love4prompts", url: SITE_URL },
          description:
            "The Terms of Use governing access to and use of love4prompts.",
          dateModified: "2026-06-01",
        }),
      },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <LegalShell title="Terms of Use" updated="June 2026">
      <Section n="1" title="Acceptance">
        <p>
          By accessing or using love4prompts, you agree to comply with and be
          bound by these Terms of Use. By using this website, you also agree to
          our <Link to="/privacy" className="underline">Privacy Policy</Link>{" "}
          and acknowledge that your data may be processed by our third-party
          service providers as described therein. If you do not agree to these
          terms, please do not use the tool.
        </p>
      </Section>

      <Section n="2" title="What love4prompts is">
        <p>
          love4prompts is a free AI prompt enhancement toolkit. We provide
          AI-generated suggestions to help structure your prompts for
          third-party AI models. Because AI output is dynamic, results are
          provided "as is" and are not guaranteed to be accurate, complete, or
          suitable for any specific context.
        </p>
      </Section>

      <Section n="3" title="Acceptable use">
        <p>You agree to use this tool responsibly. You explicitly agree not to:</p>
        <ul className="list-disc pl-6 mt-3 space-y-2">
          <li>Use the tool to generate prompts designed to create harmful, illegal, abusive, or malicious content.</li>
          <li>Attempt to reverse engineer, scrape, or systematically exploit the backend API.</li>
          <li>Use automated scripts or bots to mass-generate prompts through the service.</li>
          <li>Misrepresent AI-generated content as human-written in contexts where that distinction is required.</li>
        </ul>
      </Section>

      <Section n="4" title="Intellectual property">
        <ul className="space-y-3">
          <li><strong>Your input:</strong> The raw prompts you type remain yours. We do not claim ownership over any text you enter.</li>
          <li><strong>AI output:</strong> The enhanced output generated by our tool is yours to use, copy, and modify freely.</li>
          <li><strong>Platform rights:</strong> The love4prompts name, logo, site architecture, and product designs are owned by eMitra Technologies and are protected by intellectual property laws.</li>
        </ul>
      </Section>

      <Section n="5" title="User-generated content">
        <p>
          We do not take any guarantee of the content uploaded, submitted, or
          shared by users on our platform. All user-generated content is the
          sole responsibility of the person from whom such content originated.
          We do not endorse any user content and disclaim any liability in
          connection with it.
        </p>
      </Section>

      <Section n="6" title="Disclaimer">
        <p>
          This service is provided "as is" and "as available" without
          warranties of any kind. We do not guarantee uninterrupted or
          error-free service and are not liable for any direct, indirect, or
          consequential damages arising from your use of the toolkit.
        </p>
      </Section>

      <Section n="7" title="Contact">
        <p>
          If you have any questions or feedback regarding these terms, reach
          out to us at{" "}
          <a className="underline" href="mailto:nishchaydev@outlook.com">
            nishchaydev@outlook.com
          </a>.
        </p>
      </Section>
    </LegalShell>
  );
}

/* ───────── Shared shell + section primitives ───────── */
export function LegalShell({
  title,
  updated,
  children,
}: {
  title: string;
  updated: string;
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-dvh bg-background text-foreground font-sans antialiased">
      <header className="sticky top-0 z-40 border-b border-border bg-background/85 backdrop-blur-md">
        <div className="mx-auto max-w-3xl px-6 py-4 flex items-center justify-between">
          <Link
            to="/"
            className="inline-flex items-center gap-2 text-sm font-medium text-foreground/70 hover:text-foreground transition"
          >
            <ArrowLeft className="size-4" /> Back
          </Link>
          <span className="font-display font-bold text-base">{title}</span>
          <span className="w-10" />
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 pt-12 pb-24">
        <article aria-labelledby="legal-title">
          <div className="text-xs uppercase tracking-[0.2em] text-foreground/55 mb-3">
            Legal
          </div>
          <h1
            id="legal-title"
            className="font-display font-black tracking-tight text-4xl md:text-5xl uppercase"
          >
            {title}
          </h1>
          <p className="mt-3 text-sm text-foreground/60">
            Last updated:{" "}
            <time dateTime="2026-06-01">{updated}</time>
          </p>

          <div className="mt-10 space-y-10 text-foreground/80 leading-relaxed">
            {children}
          </div>
        </article>

        <nav
          aria-label="Legal pages"
          className="mt-16 pt-8 border-t border-border flex flex-wrap gap-3 text-sm"
        >
          <Link to="/terms" className="text-foreground/70 hover:text-foreground underline">
            Terms of Use
          </Link>
          <span className="text-foreground/30" aria-hidden="true">·</span>
          <Link to="/privacy" className="text-foreground/70 hover:text-foreground underline">
            Privacy Policy
          </Link>
          <span className="text-foreground/30" aria-hidden="true">·</span>
          <Link to="/guest" className="text-foreground/70 hover:text-foreground underline">
            Non-User Notice
          </Link>
        </nav>
      </main>
    </div>
  );
}

export function Section({
  n,
  title,
  children,
}: {
  n: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="border-t border-border pt-8">
      <div className="flex items-baseline gap-3 mb-4">
        <span className="font-display text-sm font-medium text-foreground/55">
          {n}
        </span>
        <h2 className="font-display font-black tracking-tight text-2xl md:text-3xl">
          {title}
        </h2>
      </div>
      <div className="text-foreground/80">{children}</div>
    </section>
  );
}
